runtime: go118
env: standard

# app-secrets should be created by a step in GitHub Actions.
# See .github/workflows/gae-deploy.yml for more details.
includes:
- app-secrets.yaml

handlers:
- url: /.*
  script: auto
