runtime: go112
env: standard

# # This script is supposed to be called from GitHub Actions.
# # All the secrets should be provided by GitHub Repo Secrets.
# includes:
# - app-secrets.yaml

handlers:
- url: /.*
  script: auto
